### ISSUE TITLE
Update Mysql Dogu for Easyredmine 11

### ISSUE THREAD

**Issue by nhinze23** [cloudogu/mysql#1]
The mysql dogu is very old. In order to work with easyredmine 11 it should be updated to a new version.

**Comment by ppxl** [comment]
Closing this issue in favour of a new repository see (cloudogu/mariadb#1) in order to emphasize the development of an open source dogu (MySQL is basically proprietary software from Oracle, the available open source branch of MySQL is MariaDB)
